### ISSUE TITLE
Request for LaTeX Source Code

### ISSUE THREAD

**Issue by skylee03** [benluiwj/NUS-CHEATSHEET#1]
Thanks for your generous sharing! Could you please upload the `.tex` files as well? This will make it easier for me to customize the cheatsheets. Thank you in advance!

**Comment by benluiwj** [comment]
hey, I can email it to you if that is ok

**Comment by benluiwj** [comment]
> Thanks for your generous sharing! Could you please upload the `.tex` files as well? This will make it easier for me to customize the cheatsheets. Thank you in advance!

are there particular cheatsheets youre looking at?

**Comment by skylee03** [comment]
> > Thanks for your generous sharing! Could you please upload the `.tex` files as well? This will make it easier for me to customize the cheatsheets. Thank you in advance!
> 
> are there particular cheatsheets youre looking at?

I just found out that the cheatsheet for CS4211 consists mostly of screenshots, so I don't really need them now, but thanks for your sharing anyway.
